name: TunamaRPG
version: 0.1.08
description: Un plugin RPG completo para Paper Minecraft
author: Tunama
main: com.irdem.tunama.TunamaRPG
api-version: '1.21'

softdepend:
  - Vault
  - Essentials
  - PlaceholderAPI
  - LuckPerms

commands:
  rpg:
    description: Comando principal del plugin RPG
    usage: /rpg <subcomando>
    aliases: [tunamarpg]
  
  clase:
    description: Gestionar tu clase
    usage: /clase <subcomando>
  
  raza:
    description: Ver información de tu raza
    usage: /raza
  
  subclase:
    description: Gestionar tu subclase
    usage: /subclase <subcomando>
  
  habilidades:
    description: Activa la barra de habilidades
    usage: /habilidades
    aliases: [skills]
  
  mision:
    description: Ver tus misiones
    usage: /mision <subcomando>
  
  logro:
    description: Ver tus logros
    usage: /logro
  
  estadisticas:
    description: Ver tus estadísticas
    usage: /estadisticas [jugador]
  
  top:
    description: Ver el top de usuarios
    usage: /top <tipo>
  
  clan:
    description: Gestionar tu clan
    usage: /clan <subcomando>
  
  equipo:
    description: Abrir el menú de equipo
    usage: /equipo

permissions:
  rpg.admin:
    description: Permiso de administrador del plugin
    default: op

  rpg.user:
    description: Permiso de usuario del plugin
    default: true

  rpg.characters.1:
    description: Permite 1 personaje
    default: true

  rpg.characters.3:
    description: Permite 3 personajes
    default: false

  rpg.characters.5:
    description: Permite 5 personajes
    default: false

  rpg.characters.10:
    description: Permite 10 personajes
    default: false

  rpg.characters.20:
    description: Permite 20 personajes
    default: false

  rpg.pets:
    description: Permite usar el sistema de mascotas
    default: false
